apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flaskdemo
  name: flaskdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskdemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flaskdemo
    spec:
      containers:
      - image: deepakc826/task2:17
        name: flaskdemo
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: flaskdemo
---
# aadded later
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flaskdemo
  labels:
    name: flaskdemo
spec:
  ingressClassName: nginx
  rules:
  - host: todo.task2.devopshub.tech
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: flaskdemo
            port: 
              number: 8000

